version: '3'
services:
  client:
    image: "opendigitaltwin/dt-client-bytes:latest"
    depends_on:
      - mqtt-broker
      - twin
    environment:
      - RUST_LOG=info
      - MQTT_BROKER_ADDRESS=mqtt-broker
      - MQTT_BROKER_PORT=1883
      - MQTT_CLIENT_QOS=1
      - MQTT_CLIENT_BUFFER_BYTE_SIZE=64
      - MQTT_CLIENT_MESSAGES_TO_SEND=1000
      - MQTT_CLIENT_MESSAGE_DELAY_MS=160
      - MQTT_CLIENT_TOPIC=38162cb0-e585-43d7-b55d-5c240b2bfb7c/3142192f-6bae-4f12-a6f3-5464dc37e790/d0a71d84-b80f-4558-beac-8887750652e3
    networks:
      - default
    deploy:
      replicas: 1
      placement:    
        constraints:
          - node.labels.name==client
    command: dt-client-bytes
  twin:
    image: "opendigitaltwin/dt-instance:latest"
    depends_on:
      - mqtt-broker
      - scylla-db
    environment:
      - MQTT_BROKER_ADDRESS=mqtt-broker
      - MQTT_BROKER_PORT=1883
      - MQTT_INSTANCE_QOS=1
      - RUST_LOG=info
      - DB_ADDRESS=scylla-db:9042
      - TWIN_INSTANCE=38162cb0-e585-43d7-b55d-5c240b2bfb7c
    networks:
      - default
    restart: always
    deploy:
      placement:    
        constraints:
          - node.labels.name==cloud
    command: dt-instance
  mqtt-broker:
    image: "eclipse-mosquitto:1.6.10"
    networks:
      - default
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
      - /mosquitto/log:/mosquitto/log
      - /mosquitto/data:/mosquitto/data
    restart: always
    deploy:
      placement:
        constraints:
          - node.labels.name==cloud
  scylla-db:
    image: scylladb/scylla
    networks:
      - default
    volumes:
      - /var/lib/scylla:/var/lib/scylla
    deploy:
      placement:
        constraints:
         - node.labels.name==cloud
networks:
  default:
